### ISSUE TITLE
Entity field types nullable or not?

### ISSUE THREAD

**Issue by BananeGuimauve** [jhipster/jhipster-dotnetcore#17]
In the Java version, the types proposed for the fields of the entities are nullable but one can add to these fields an Required annotation.
In C #, equivalent types are not nullable unless you add the suffix "?" (example: int?). Similarly, the [Required] annotation can be added to the fields.
The question raised here is to know if we should keep the default behavior of the types (not nullable) or add the suffix "?" to get exactly the same behavior as the Java version.

**Comment by danielpetisme** [comment]
What's the expected behavior in the common .Net frameworks. 
From what I have seen it typescript (which is close to the .Net world), the fields are often `?` suffixed (have a look to the JHipster frontend entities.
So for me, it would be `?` where ever we can and enforced by `[Required]` for business/domain rules.

**Comment by BananeGuimauve** [comment]
I closed this issue because I already implemented the suffix `?` to the field types earlier. So we don't need to change anything. :)
