### ISSUE TITLE
Refactoring question about Data folder

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#297]
This question is about the data folder (with the ApplicationDatabaseContext class and extensions).

Should it be moved to infrastructure layer or somewhere else?

I did a little test locally (have not pushed yet):
![image](https://user-images.githubusercontent.com/891084/87077274-44973880-c1f9-11ea-8fec-1f3f3923143a.png)

It allowed me to implement service layer without compilation errors while the repository layer is not implemented.

**Comment by nicolas63** [comment]
Yes, that's exactly right. In the infrastructure layer there is dbcontext and repositories

**Comment by ivanmonteiro** [comment]
> Yes, that's exactly right. In the infrastructure layer there is dbcontext and repositories

What about Services? It would be a separate layer?

**Comment by nicolas63** [comment]
Services is in domain layer 
Maybe you can have one folder for services and an other for entities. And a subfolder for services interfaces

**Comment by ivanmonteiro** [comment]
> Services is in domain layer
> Maybe you can have one folder for services and an other for entities. And a subfolder for services interfaces

Having services and domain on the same project might be problematic because of dependencies. If any of the dependencies of services are not compatible with .net standard (so you can reuse the library with blazor). 

But I can give it a try

**Comment by nicolas63** [comment]
All services must be compatible with .netstandard. If it's not, there's a problem. This layer is the business logic so it's not shared with blazor

**Comment by maznag** [comment]
For me Domain or DB entities have to be with Data Layer (or Repository) that include DBContext.

I propose this architecture to refactor the structure of the project.:

- ProjectName.Common (Actually JHipsterNet project; I prefer to rename it to Common)
- ProjectName.Crosscutting
- ProjectName.Models (for all DTOs and VM objects)
> +-- Dto
> +-- VM
- ProjectName.Data or Repository => for Domain and Data Layer
> +-- Config (DatabaseContext and DataBaseConfiguration; Startup)
> +-- Domain
> +-- Extensions
> +-- Repository ==> For me, we it's not necessary to add UnitOfWork and Repositories for each Domain entity (we can use directly databaseContext)
- ProjectName.Service
> +-- Interfaces
> +-- Service
> +-- Mapper
- ProjectName.WebApp ==> for Web Api and Angular App
> +-- Config (or Infrastructure)
> +-- Controllers
> +-- ClientApp
- ProjectName.Tests

What do you think ?

**Comment by ivanmonteiro** [comment]
> For me Domain or DB entities have to be with Data Layer (or Repository) that include DBContext.
> 

I usually prefer a separate project for our entities (projectName.Domain)

> I propose this architecture to refactor the structure of the project.:
> 
> * ProjectName.Common (Actually JHipsterNet project; I prefer to rename it to Common)

I like this.

> * ProjectName.Crosscutting
> * ProjectName.Models (for all DTOs and VM objects)
> 
> > +-- Dto
> > +-- VM
> 

It makes sense. In dotnet we usually refer to Models instead of DTOs (lets be honest, Models serve the same function as DTOs just with a different name). Since dotnet apis use the MVC pattern it makes sense to call it Models instead of VM or Dtos.
It is a question of deciding if we want to be more like the java version or to use a nomenclature more natural for dotnet developers.


> * ProjectName.Data or Repository => for Domain and Data Layer
> 
> > +-- Config (DatabaseContext and DataBaseConfiguration; Startup)
> > +-- Domain

I prefer a separate domain project.

> > +-- Extensions
> > +-- Repository ==> For me, we it's not necessary to add UnitOfWork and Repositories for each Domain entity (we can use directly databaseContext)
> 
I agree about repository.

> * ProjectName.Service
> 
> > +-- Interfaces
> > +-- Service
> > +-- Mapper
> 
I like having a separate service project.

> * ProjectName.WebApp ==> for Web Api and Angular App
> 
> > +-- Config (or Infrastructure)
> > +-- Controllers
> > +-- ClientApp
> 
> * ProjectName.Tests
> 
> What do you think ?

I really agree with you on this point about why using repositories. DbContext implements both repository and unit of work patterns, so building around them only adds abstraction on top of abstraction. All database related code would be on one place but it tends to grow too large (hundreds of lines) when projects getts bigger and needs more queries. 

And things like including child relationship in one query to avoid N+1 gets complicated because we need to add one more method to our (already too big) repository. Or adding a new complex query.

Maybe make repository accept a query object so it does not get too big (see https://www.hojjatk.com/2018/08/query-object-pattern.html)?

Sometimes we want all our code including dbcontext inside the controller or service because it is all simple code and we know it will not get bigger. 

Maybe make repository optional with a prompt?

**Comment by nicolas63** [comment]
> > For me Domain or DB entities have to be with Data Layer (or Repository) that include DBContext.
> 
> I usually prefer a separate project for our entities (projectName.Domain)

I prefer separate too, if DbContext is in Domain project, entities and persistence are strongly coupled

> > I propose this architecture to refactor the structure of the project.:
> > 
> > * ProjectName.Common (Actually JHipsterNet project; I prefer to rename it to Common)
> 
> I like this.

Or keep the name and do this (https://github.com/jhipster/jhipster-dotnetcore/issues/49) 


> > * ProjectName.Crosscutting
> > * ProjectName.Models (for all DTOs and VM objects)
> > 
> > > +-- Dto
> > > +-- VM
> 
> It makes sense. In dotnet we usually refer to Models instead of DTOs (lets be honest, Models serve the same function as DTOs just with a different name and context). Since dotnet apis use the MVC pattern it makes sense to call it Models instead of VM or Dtos.
> It is a question of deciding if we want to be more like the java version or to use a nomenclature more natural for dotnet developers.

DTO is very used in dotnet world, in our case models do not make sense. Model and view model are for the view, like Blazor for example. 
It is used in project with razor because it's client part. Here we have an api so it's DTO 


> > * ProjectName.Data or Repository => for Domain and Data Layer
> > 
> > > +-- Config (DatabaseContext and DataBaseConfiguration; Startup)
> > > +-- Domain
> 
> I prefer a separate domain project.

Yes, I prefer Domain and Infrastructure 

> > > +-- Extensions
> > > +-- Repository ==> For me, we it's not necessary to add UnitOfWork and Repositories for each Domain entity (we can use directly databaseContext)
> 
> I agree about repository.

I'm not agree with you if you use Directly DbContext it's difficult to mock it for unit test, and it's not service role to make request 

> > * ProjectName.Service
> > 
> > > +-- Interfaces
> > > +-- Service
> > > +-- Mapper
> 
> I like having a separate service project.

I'm not agree too , domain service is business logic like entity so it's normal to have this in same folder.
The mapping in not in domain service layer, it's only the entities in the services.
In you want an intermediate layer it's application layer with application service, in this layer you can do the mapping. But it's more complex

![image](https://user-images.githubusercontent.com/14818936/87125683-33970780-c28b-11ea-9d31-4ed4ba4cfae7.png)


>     * ProjectName.WebApp ==> for Web Api and Angular App
> 
> 
> > +-- Config (or Infrastructure)
> > +-- Controllers
> > +-- ClientApp
> 
>     * ProjectName.Tests
> 
> 
> What do you think ?

Totally agree with that 

> Maybe make repository optional with a prompt?

we can do this but it's more complicate to maintain and i think this layer is very important, yes it add abstraction but it's necessary. It's necessary for unit tests or for other databases like mongo. If you do simple operation the DbContext is enough but quickly you need custom requests and their place is in the repositories

**Comment by nicolas63** [comment]
A small precision about repositories, the repositories interfaces is in domain layer and implementation in infra layer

**Comment by maznag** [comment]
@nicolas63 I see that you are too inspired by this architectural scheme that you propose each time and you absolutely want to implement it. Frankly I don't agree with that.

It is not because everyone implements unit of work and repository interfaces that we will do it. Still we have database specific implementations for both of these available with DbContext class.

It's just a personal opinion and I have nothing against you :-)

I'm not agree too to propose make repository optional because it's more complicate to maintain.

**Comment by nicolas63** [comment]
> @nicolas63 I see that you are too inspired by this architectural scheme that you propose each time and you absolutely want to implement it. Frankly I don't agree with that.

Yes because i think is good way (it's my opinion too) but we can discuss it. If you don't create repository it's difficult to do unit test you can use inmemory database but i prefer mock a repository to test only service layer for example 

The unit of work is not a problem because it's DbContext, we can just add interface like (https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs)

**Comment by maznag** [comment]
We can continue to use extension methods for generic Code and add the Transaction notion rather than implement a Custom DB Context for each entity

**Comment by nicolas63** [comment]
I don't want a custom DbContext per entity just one generic repository who each specific repository implement and add custom logic if necessary. 
With ef extensions methods if you use directly is hard to mock for unit test. 
Today controller have the logic to query, attach, detach , includes entity. I think it's too much for controller or service and repository layer can do this

**Comment by maznag** [comment]
> I don't want a custom DbContext per entity just one generic repository who each specific repository implement and add custom logic if necessary.

OK for generic repository 

> With ef extensions methods if you use directly is hard to mock for unit test.
> Today controller have the logic to query, attach, detach , includes entity. I think it's too much for controller or service and repository layer can do this

Normally all the Db context code in the controllers will be migrated to the service Layer

```
public async Task<ActionResult<ProjectDemoDto>> Create([FromBody] ProjectDemoDto projectDemoDto)
        {
            _log.LogDebug($"REST request to save ProjectDemo : {projectDemoDto}");
            if (projectDemoDto.Id != 0)
                throw new BadRequestAlertException("A new projectDemo cannot already have an ID", EntityName, "idexists");

            ProjectDemoDto projectDemo = await _projectDemoService.Create(projectDemoDto);            
            return CreatedAtAction(nameof(GetById), new { id = projectDemo.Id }, projectDemo)
                .WithHeaders(HeaderUtil.CreateEntityCreationAlert(EntityName, projectDemo.Id.ToString()));
        }
```
Service

```
public async Task<ProjectDemoDto> Create(ProjectDemoDto projectDemoDto)
        {
            _log.LogDebug($"REST request to save ProjectDemo : {projectDemoDto}");
            ProjectDemo projectDemo = _mapper.Map<ProjectDemo>(projectDemoDto);
            _applicationDatabaseContext.ProjectDemos.Add(projectDemo);
            await _applicationDatabaseContext.SaveChangesAsync();
            return _mapper.Map<ProjectDemoDto>(projectDemo);
        }
```
For tests, I use service rather than dbContext But effectively I have a problem for Update method (attach detach, ..) . So I use Dbcontext only for update (I don't have too much time to look at it in detail :-) and I use it like that :-) )

`var updatedProjectDemo = await _applicationDatabaseContext.ProjectDemos.SingleOrDefaultAsync(it => it.Id == createdProject.Id);`

**Comment by nicolas63** [comment]
Okay, what I propose is let @romain325 advance on the repo layer (#276)  and review this with me.
