### ISSUE TITLE
Migration to ef core 5 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#348]
##### **Overview of the feature request**

The most important issue is treated (https://github.com/dotnet/efcore/issues/19003) 

##### **Motivation for or Use Case**

We have hack for do many to many without navigation with ef core 5 we can remove all the hack 😃 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
I'm interested on working on this, especially because of the many-to-many feature of EF Core 5 that will be of great benefit.
I have made some tests and EF is not coupled to the .Net version.
Maybe you, @nicolas63, can work on the migration to .net 5 and I can work on this issue (EF5 and many-to-many support)?

**Comment by nicolas63** [comment]
@ivanmonteiro yes totally agree with you it would be a good step forward for the project !
