### ISSUE TITLE
Blazor sample app repository

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#382]
@jdubois 

Can you create a sample repository for blazor app (#165) ? 
We can named it jhipster-sample-app-blazor 

Can you also create the project on sonarcloud please ? 

thank you

**Comment by jdubois** [comment]
- I created the repo at https://github.com/jhipster/jhipster-sample-app-blazor and gave the permissions to the .NET teams (so it should be all good for you @nicolas63 )
- I created the Sonarcloud project at https://sonarcloud.io/project/configuration?id=jhipster_sample-app-blazor and gave you permissions

-> I hope it's OK, please mention me otherwise!

Also, I saw your request about allowing ReadTheDocs to access the organization, but it would allow it to read private data, so I'm reluctant to do this. Do you need this for writing the documentation?

**Comment by nicolas63** [comment]
Thank you @jdubois ! For readthedocs, sorry for the request, you can refuse it. I configured this manually and everything works now.

**Comment by nicolas63** [comment]
@jdubois Can you give me admin right on https://sonarcloud.io/project/configuration?id=jhipster_sample-app-blazor  and on https://sonarcloud.io/dashboard?id=jhipster_jhipster-sample-app-dotnetcore ?

**Comment by jdubois** [comment]
Awesome! @nicolas63 you should be admin on both projects
