### ISSUE TITLE
[CD] Deploy generated app in Azure App Service 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#388]
##### **Overview of the feature request**

Deploy generated app to Azure App Service 

sample project 
https://github.com/Azure-Samples/dotnet_core_sample

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by A-5ingh** [comment]
@nicolas63 I can pick this task up.

**Comment by nicolas63** [comment]
Thanks, do you need help ?

**Comment by A-5ingh** [comment]
Yes please @nicolas63 if you could provide more details on the requirement.
From the description I could understand is that we need to deploy the generated app to AzureApp service. 
We will have an ARM template to generate the required resources in Azure but to deploy we might require devops pipeline right ? or maybe we can use an existing git url to deploy the app.

**Comment by nicolas63** [comment]
For resources creation we can use a template or also generate terraform files to create resources ( sample here : https://gitlab.com/lips63/achievements/-/merge_requests/5/diffs#800d400dc35711ca737e1ffc8d80b40a6cff73ef ) 
For the deployment i think the first step is to create a script. In other issue we can call this script to deploy automatically 
After that we need to add this on the generation for this you can add a question here (https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/prompts.js) and add files here https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/files.js with condition to only generate this files when the user choose yes. 
Is this okay with you ?

**Comment by A-5ingh** [comment]
Sure @nicolas63 let me go through this Terraform first and how to use let. Once I'll have the terraform files ready then we can pick the script. For now I'm just going to note down the steps which we will need to perform.

- [ ] Create a Terraform script to be used for creation of resources in Azure. We have ARM template in azure for resource creation.
- [ ] Create a script to call the terraform script created in previous step
- [ ] On user selection of azure deployment will create a new folder or place the script in root folder of generated app.

**Comment by nicolas63** [comment]
that's right if you need help don't hesitate

**Comment by A-5ingh** [comment]
@nicolas63 I have accomplished the below tasks so far:

- [x] Generated a sample app using dotnetcore blueprint.
- [x] Deployed locally using docker-compose and published an image of the same on a public docker repository. (Found an issue in docker-compose build command, will raise a separate issue for that)
- [x] Created terraform files (main.tf and variables.tf) which will create an App Service and Azure SQL Server with firewall settings to allow connection from azure IP.
- [x] Tested the terraform init, plan, apply and destroy commands.
- [x] WebApp successfully deployed to app services using above commands.
<img width="1797" alt="Screen Shot 2021-04-02 at 1 42 40 PM" src="https://user-images.githubusercontent.com/32884734/113396571-576e2080-93b9-11eb-9464-f4c2699ef236.png">

**Comment by nicolas63** [comment]
Very nice ! Can you create a repo with this ? or create a zip ? After a look I could help you to put it in the generator

**Comment by nicolas63** [comment]
(Found an issue in docker-compose build command, will raise a separate issue for that) => i have see this problem it's fixed now but not released

**Comment by A-5ingh** [comment]
> Very nice ! After a look I could help you to put it in the generator

Thank you @nicolas63. So the terraform scripts will work for an Azure SQL server, we will have to see how can we make it configurable for other databases which jhipster supports (like mysql, postgre and oracle). Also, let me know if the documentation has to be updated for the deployment in azure.

**Comment by A-5ingh** [comment]
> (Found an issue in docker-compose build command, will raise a separate issue for that) => i have see this problem it's fixed now but not released

Oh is it. The issue I found was due to BuildTarget and was resolved by copying the file (Directory.Build.targets) in dockerfile just before restore command.

**Comment by ivanmonteiro** [comment]
@A-5ingh I have not used Terraform yet but it is a very interesting approach. Please keep going and if you need some help don't hesitate to ask.

**Comment by A-5ingh** [comment]
> @A-5ingh I have not used Terraform yet but it is a very interesting approach. Please keep going and if you need some help don't hesitate to ask.

Thanks @ivanmonteiro. Yes, Terraform is a unique way of creating the resources on any of the clouds (either AWS or Azure). 
@nicolas63 I have made the required changes for prompting the user and then generating the tf files required to create the resources and then deploy using docker image which the user has to build and push to either dockerhub or azure or any other docker service.
I have created this branch on the forked repository - https://github.com/A-5ingh/jhipster-dotnetcore/tree/deploy-on-azure-terraform

Steps to follow:
1. Generate a monolithic app with sql server as database and select yes to generate terraform scripts.
2. Use docker-compose command to build the docker image. `docker-compose -f docker/app.yml build`
3. Then tag the image built in above step using `docker tag <source-image> <destination-image>:version/tag`
4. Push the image to docker hub or any docker service provider using `docker push <destination-image>:version/tag`. _Note_: The docker image link and its tag will use as input to terraform variables.
5. Make sure terraform cli is installed on your system. Refer to https://www.terraform.io/downloads.html
6. Change directory to terraform folder - `cd terraform` from root directory.
6. First login into your azure cli by using `az login`. Terraform plan command will work only if the user is authenticated using azure cli.
7. Execute below terraform commands to create resources (Azure app service, azure sql) and deploy as a docker image to app service:
   1. `terraform init`
   2. `terraform plan -out "MyAppPlan"` You can choose any name instead of MyAppPlan.
   3. `terraform apply "MyAppPlan"` This will create the resources and then provide you the link to your deployed app as output variable.

Faced couple of issues while running the blueprint (I have cloned my branch from main branch):
1. ClientApp/tsconfig.e2e.json doesn't exist error but app got generated and was able to run without any issue.
2. Unable to stop prettier plugin from auto formatting ejs file format.

**Comment by nicolas63** [comment]
Hi @A-5ingh, I have looked your changes all seem ok. 
For the issue : 
ClientApp/tsconfig.e2e.json doesn't exist error but app got generated and was able to run without any issue.
It's due to v7 migration i need to remove one replace but it's not a problem for the generation.

Unable to stop prettier plugin from auto formatting ejs file format.
I don't understand this, can you give me more detail ? 

On cloning from main branch there is some issue with the file /docs/assets/blazor-choice.PNG. I was unable to revert the change or even commit it. So I had to delete the file and add it again. Most likely a naming issue with the file is there.
I have the same issue i need to investigate. 

For the next step can you open the PR and add the documentation on terraform in docs please ? 
For other database there are two possibilities : 
You can add it here or you can open another issue for this.

**Comment by A-5ingh** [comment]
#672 PR created for azure. But I accidentally added the docs in main branch. So will update the PR again.
