### ISSUE TITLE
Migrate to .Net Core 3.0

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-dotnetcore#43]
.Net Core 3.0 is now public with cool a cool feature list:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/

A .net core hipster must use 3.0 to be in the cutting edge 😄

**Comment by jdubois** [comment]
I added a $100 bug bounty on this

**Comment by vraravam** [comment]
I have installed `generator-jhipster-dotnetcore@0.1.0` - but, this is still generating code that targets .net core 2.2. This issue is merged, and says there's support for v3 - but, that's not the observed behavior. IS there a new release of the package that I need to upgrade to? Or is there a release planned for supporting .net core 3.x?

**Comment by danielpetisme** [comment]
Thank you for raising the problem.
@nicolas63 would you mind to have an eye on it please?

**Comment by vraravam** [comment]
Update: Since I had the released version (0.1.0) installed and linked via `npm` - I think it had taken that installation. I have since uninstalled that version, reinstalled (not globally) and then tried the latest HEAD of master - and things seem better. Ther  are still 2 issues that I can see:
1) I am forced to use the `--skip-checks` command-line switch
2) The `AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2)` is still set in the generated code. This might not be a breaker - but, wanted to point it out here

**Comment by nicolas63** [comment]
The npm package was not publish because the travis build failed on all build ...
Who can help me to fix it ? 
Yes the .SetCompatibilityVersion(CompatibilityVersion.Version_2_2) is unused since dotnet core 3.0 so i can remove it.

**Comment by nicolas63** [comment]
Now travis build was fix but the package was not publish on https://www.npmjs.com/package/generator-jhipster-dotnetcore. @danielpetisme could you and this phase to travis ? https://docs.travis-ci.com/user/deployment/npm/

**Comment by maznag** [comment]
@nicolas63  the build failed since your commit #66. As the package generator-jhipster-dotnetcore@0.2.0 was not publish, unable to execute "npm install".

@nicolas63 @danielpetisme can you check please ?

**Comment by nicolas63** [comment]
The build is now ok but the package was not publish since 5 Months see https://www.npmjs.com/package/generator-jhipster-dotnetcore

**Comment by nicolas63** [comment]
Can we discuss in other issue. The .net core 3 migration is ok but not publish

**Comment by danielpetisme** [comment]
You mean I have to work 🤣

**Comment by nicolas63** [comment]
Yes :wink: i have create #71

**Comment by mohamedsogoba** [comment]
please i need to install

**Comment by danielpetisme** [comment]
Hello,

You should find all the details on the Readme.md

First you need Jhipster installed and then you can install the blueprint`

`npm install -g generator-jhipster-dotnetcore`

Once there you should be able to run
`jhipster --blueprint dotnetcore`

Le lun. 10 févr. 2020 à 21:41, mohamedsogoba <notifications@github.com> a
écrit :
