### ISSUE TITLE
Add possibility to audit entities 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#48]

**Comment by danielpetisme** [comment]
The last time I checked this question, I did not find any suitable lib to audit entities.

@nicolas63 do you know anything that could help us to move forward, otherewise I close the issue.

**Comment by nicolas63** [comment]
yes, there is https://github.com/thepirat000/Audit.NET or the other way is to override SaveChange in DbContext and add audit informations on entity who implement the IAuditableEntity interface

**Comment by nicolas63** [comment]
https://www.entityframeworktutorial.net/faq/set-created-and-modified-date-in-efcore.aspx
we can also add created by and updated by

**Comment by ivanmonteiro** [comment]
It would be nice if the user can choose if the entitiy will be auditable or not.

**Comment by nicolas63** [comment]
Yes it is pretty easy to add with this  (https://www.entityframeworktutorial.net/faq/set-created-and-modified-date-in-efcore.aspx)

**Comment by ivanmonteiro** [comment]
@nicolas63 I like this feature, but I think it should not be mandatory. 
What I mean is that the user/developer should be able to choose if he wants entities to be auditable or not. 
The reason is that retrieving and updating the rows (addedDate/UpdatedDate) has some cost to it, when adding/updating entities and when listing entities the added/updated information will be retrieved adding more data transfer between app/db and a little bit more query time.
I would like to be able to choose if entities will be auditable or not.

So, finally:
Do you think that adding a question at the CLI is a good option for this?
Should it be per-entity basis or per-application?

**Comment by nicolas63** [comment]
For me, it is complex and unnecessary to add a question. I think the generated application can just expose this functionality and if users want an audible entity, they can add the interface in their entities. 
By default no entity is audited. 
Do you agree with this ?

**Comment by ivanmonteiro** [comment]
> For me, it is complex and unnecessary to add a question. I think the generated application can just expose this functionality and if users want an audible entity, they can add the interface in their entities.
> By default no entity is audited.
> Do you agree with this ?

I agree, I seems reasonable to me.
So if the user/developer want one entity to be auditable, he/she would manually change the generated entity to inherit from a base entity:
```
public class Employee: AuditableEntity
{
    long Id {get; set;}
    string Name {get; set;}
    ...
}
```

And DbContext shoud take care of updating those fields "automatically" when SaveChanges is called.

**Comment by nicolas63** [comment]
Yes exactly
