### ISSUE TITLE
clientApp files in root app folder

### ISSUE THREAD

**Issue by kosnkow** [jhipster/jhipster-dotnetcore#74]
files of angular client app (package.json, tsconfig, node_modules etc) exist in main root app together with c# models, controllers ets. 
Shuouldn't be moved to clientApp ?

**Comment by maznag** [comment]
we can also re-organize the entire structure of the generated application.  I’ll think about that and suggest a new structure

**Comment by kosnkow** [comment]
exactly, after we add mongo support which is like 70% done, that would be probably next task, besides moving client app entirely to other folder we would also split whole app into more projects since now almost everything exists in one.

**Comment by ItsInsajd** [comment]
I agree, keeping every layer in one project seems a bit messy, although it's okay for smaller apps.

**Comment by nicolas63** [comment]
I'am agree too. We can also extract shared project in nuget package see #49

**Comment by danielpetisme** [comment]
I propose to focus on the original question and discuss the structure in a dedicated issue.

**Comment by ivanmonteiro** [comment]
Maybe creating one folder with all things related to the client app. And on another folder all backend related files. Using --skip-server and --skip-client is not that straightforward to those who are new to jhipster. 

The frontend could be switched to a separated folder like:
frontend/
frontend/src/
frontend/src/app/
...
frontend/package.json
...

Also one thing to think about is the backend's folder structure because it follows the java version's folder strucutre (src folder and all the code inside it). In most .Net projects I see a strucutre of Controllers, Models, etc... inside the project's folder and no src folder. Although it would be simpler to implement using the current structure with the src folder and just switching the frontend or backend to a different folder.

Here is a sketch of what it could be for the backend (without the src folder):
backend/
backend/Controllers/
backend/Models/
...
backend/backend.csproj
...
