### ISSUE TITLE
Generating entities from model

### ISSUE THREAD

**Issue by kosnkow** [jhipster/jhipster-dotnetcore#80]
Hi, in original jhipster for java it is possible to generate entities from JDL model.
Is it possible in dotnet blueprint, or was there any idea to let say create cs file with list of classes and then recreate all entities ? I think that would be nice.

**Comment by danielpetisme** [comment]
We did not investigate how to use JDL directly with the dotnet blueprint.

Feel free to have a look!! I would be interested by the feasability (since we can already generate entities and relations I think from a pure technical standpoint is not impossible.

While I'm sure we can have a technical support I'm  sure it won't be very idomatic. The JDL uses Java-oriented keywords (like mapstruct for DTO), I'm not very comfortable to ask to a .Net dev to use these kinds of keywords.

Defnitively an area to explore, go for it.

**Comment by nicolas63** [comment]
The command jdl import already work because this command call entity generator, i close this issue
