### ISSUE TITLE
liquibase style database codebase generation

### ISSUE THREAD

**Issue by xbotuk** [jhipster/jhipster-dotnetcore#845]
Please add liquibase style database codebase generation for .Net core

**Comment by ivanmonteiro** [comment]
This is a duplicate of https://github.com/jhipster/jhipster-dotnetcore/issues/98,
It would be nice to have the generator handle migrations in some way but its been a while since the issue #98 is open

It is possible to use entity framewok to generate database migrations: https://jhipsternet.readthedocs.io/en/latest/Features/database-migrations.html
Check the documentation above :)
It is a manual process but it is fairly simple to add migrations to a project

**Comment by ivanmonteiro** [comment]
I closed this issue in favor of Issue #98
