### ISSUE TITLE
When I make a modification to the page, it does not update hot

### ISSUE THREAD

**Issue by elalejmartin** [jhipster/jhipster-dotnetcore#892]
When I make a modification to the page, it does not update hot, I have to stop the execution and raise it again. How can I get the changes to be hot?

**Comment by ivanmonteiro** [comment]
If you run `dotnet watch` command it will probably work, but take a long time since it will recompile the backend and the frontend every time a file changes.

If you're willing to split the project into backend-only and frontend-only it works better for your use case since reloading will be much faster. See: https://www.jhipster.tech/separating-front-end-and-api/

You will need to run two commands into separate terminals: `dotnet watch` and `npm start` (for angular)
